// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AichatController from "./aichat_controller"
application.register("aichat", AichatController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LiveSearchController from "./live_search_controller"
application.register("live-search", LiveSearchController)

import PlyrController from "./plyr_controller"
application.register("plyr", PlyrController)
