height: 500
menubar: true
toolbar:
  - undo redo | blocks | bold italic | codesample | alignleft aligncenter alignright | bullist numlist outdent indent | removeformat | help
plugins:
  - insertdatetime lists media table code help wordcount
   - undo redo | blocks | bold italic | alignleft aligncenter alignright | bullist numlist outdent indent | removeformat | help | code
plugins:
   - insertdatetime lists media table code help wordcount media
